apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-ingressroute-certificate
spec:
  # Secret names are always required.
  secretName: n8n-ingressroute-certificate-secret
  issuerRef:
    name: route53-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - n8n.homelab.coleduclos.io