apiVersion: v1
kind: PersistentVolume
metadata:
  name: n8n-pv-nfs
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/pool-01/kubernetes/n8n/node
    server: truenas.localdomain
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
spec:
  storageClassName: ""
  volumeName: n8n-pv-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
