apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-pvc
spec:
  storageClassName: ""
  volumeName: n8n-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
