apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-nfs
spec:
  storageClassName: ""
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/pool-01/kubernetes/n8n/postgres
    server: truenas.localdomain
    readOnly: false
  mountOptions:
    - vers=3

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pvc
spec:
  storageClassName: ""
  volumeName: postgres-pv-nfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi