kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql-pvc
spec:
  storageClassName: ""
  volumeName: n8n-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 300Gi