apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pi-hole-ingressroute-certificate
spec:
  # Secret names are always required.
  secretName: pi-hole-ingressroute-certificate-secret
  issuerRef:
    name: route53-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pihole.home.coleduclos.io