apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pi-hole-data
  labels:
    app: pi-hole
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi