apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.16.2
      helm:
        parameters:
          - name: "crds.enabled"
            value: "true"
    - repoURL: https://github.com/coleduclos/homelab.git
      targetRevision: HEAD
      path: v2/cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
