apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/coleduclos/homelab.git
      targetRevision: HEAD
      path: v2/plex
  destination:
    server: https://kubernetes.default.svc
    namespace: plex
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
