apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-assistant-ingressroute-certificate
  namespace: home-assistant
spec:
  # Secret names are always required.
  secretName: home-assistant-ingressroute-certificate-secret
  issuerRef:
    name: route53-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - hass.home.coleduclos.io