apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.17/manifests/install.yaml
  - ingress-route.yml
  - argocd-certificate.yml
  - applications/

## changes to config mapsgit co
patches:
  - path: argocd-cmd-params-cm-patch.yml
