apiVersion: v1
kind: Service
metadata:
  name: zwave-js-ui
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
    - name: websocket
      port: 3000
      targetPort: 3000
  selector:
    name: zwave-js-ui