apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zwave-js-ui-data
  labels:
    app: zwave-js-ui
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi