apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pi-hole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coleduclos/homelab.git
    targetRevision: HEAD
    path: pi-hole
  destination:
    server: https://kubernetes.default.svc
    namespace: pi-hole
  syncPolicy:
    automated: {}
