apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zigbee2mqtt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/coleduclos/homelab.git
    targetRevision: HEAD
    path: zigbee2mqtt
  destination:
    server: https://kubernetes.default.svc
    namespace: zigbee2mqtt
  syncPolicy:
    automated: {}
