apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: route53-cluster-issuer
spec:
  acme:
    email: cole.duclos@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: route53-cluster-issuer-account-key
    solvers:
    - dns01:
        route53:
          region: us-west-2
          accessKeyIDSecretRef:
            name: cert-manager-route53-credentials
            key: access-key-id
          secretAccessKeySecretRef:
            name: cert-manager-route53-credentials
            key: secret-access-key
