apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zigbee2mqtt-ingressroute-certificate
  namespace: zigbee2mqtt
spec:
  # Secret names are always required.
  secretName: zigbee2mqtt-ingressroute-certificate-secret
  issuerRef:
    name: route53-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - zigbee.home.coleduclos.io