apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-nfs-media
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti                   # < max. size we reserve for the pv. A bigger value than the configdata
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/pool-01/media            
    server: truenas.localdomain
    readOnly: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-media
  namespace: plex
spec:
  storageClassName: ""
  volumeName: plex-pv-nfs-media
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1T