apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-nfs-config
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/pool-01/kubernetes/plex            
    server: truenas.localdomain
    readOnly: false

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-config
spec:
  storageClassName: ""
  volumeName: plex-pv-nfs-config
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-nfs-media
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/pool-01/media            
    server: truenas.localdomain
    readOnly: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-media
spec:
  storageClassName: ""
  volumeName: plex-pv-nfs-media
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1T