apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-config
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv-nfs-media
spec:
  storageClassName: ""
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/pool-01/media            
    server: truenas.localdomain
    readOnly: true

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc-media
spec:
  storageClassName: ""
  volumeName: plex-pv-nfs-media
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1T